### ISSUE TITLE
How can I use this with tokio?

### ISSUE THREAD

**Issue by DevasiaThomas** [1c3t3a/rust-socketio#185]
My code runs in a tokio runtime with ``#[tokio::main(flavor = "multi_thread", worker_threads = 4)]``
connecting to a server as shown in the examples causes
<details>

```rust
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:543:12
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/shutdown.rs:51:21
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:145:12
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:162:9
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188:1
   5: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188:1
   6: reqwest::blocking::wait::enter
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/blocking/wait.rs:76:21
   7: reqwest::blocking::wait::timeout
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/blocking/wait.rs:13:5
   8: reqwest::blocking::client::ClientHandle::new
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/blocking/client.rs:996:15
   9: reqwest::blocking::client::ClientBuilder::build
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/blocking/client.rs:103:9
  10: reqwest::blocking::client::Client::new
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/blocking/client.rs:798:9
  11: rust_engineio::transports::polling::PollingTransport::new
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_engineio-0.3.1/src/transports/polling.rs:36:29
  12: rust_engineio::client::client::ClientBuilder::handshake
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_engineio-0.3.1/src/client/client.rs:142:25
  13: rust_engineio::client::client::ClientBuilder::build
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_engineio-0.3.1/src/client/client.rs:153:9
  14: rust_engineio::client::client::ClientBuilder::build_with_fallback
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_engineio-0.3.1/src/client/client.rs:262:22
  15: rust_socketio::client::builder::ClientBuilder::connect_manual
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_socketio-0.3.1/src/client/builder.rs:256:35
  16: rust_socketio::client::builder::ClientBuilder::connect
             at /home/samthomas/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_socketio-0.3.1/src/client/builder.rs:217:22
  17: sf_edge_gateway::send::start_send::{{closure}}
```

</details>

The connection does happen from within an async function(# 17) .  Any suggestions on how to approach this? I see that reqwest is trying to create its own tokio runtime internally beacuse this library uses a blocking version.

**Comment by DevasiaThomas** [comment]
Never mind I see the PR :D
